layout_spectrum: 0.16192720225080848
typography_spectrum: 0.6505376
color:
  saturation: 0.6531138140708208
  brandStrength: 0.6194478354882449
  rhythmicContrast: 0.6930837179534137
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
  lightness: 0.6523395290132612
coverPrefs:
  filter: false
content_rating:
  adult: false
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/02d50d6c-547c-41ac-805d-1dfd5722058f.png
name: Best Leads | In Person data collection
navigation:
  - name: About us
    id: 758e9194-72a1-472d-aef0-d316c36c6395
    type: content
  - name: Prices
    id: c6373ea6-adfc-4a73-a6ba-b119c91fbf96
    type: content
  - name: What we do
    id: 965d916d-7fcd-4d75-b092-5d9b63256750
    type: content
  - name: Contact us
    id: 84ac3885-1b15-44fe-a922-332432beefa7
    type: content
  - name: Customer login
    url: 'https://bestleadsnz.getdata.biz/admin/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6d9928ed-6d86-4fd9-969f-6d09eeb217c9.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: 'In person data collection '
