layout_spectrum: 0.5195754352025688
typography_spectrum: 0.9793228984344751
color:
  brandStrength: 0.23338561947457492
  lightness: 0.9626601655036211
  saturation: 0.5803182052914053
  rhythmicContrast: 0.20016674767248333
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
name: Best Leads | In Person data collection
navigation:
  - id: 758e9194-72a1-472d-aef0-d316c36c6395
    url: 2016-07-18-about-us.html
    name: About us
    type: content
  - id: c6373ea6-adfc-4a73-a6ba-b119c91fbf96
    url: 2016-07-18-prices.html
    name: Prices
    type: content
  - id: 965d916d-7fcd-4d75-b092-5d9b63256750
    url: 2016-07-18-what-we-do.html
    name: What we do
    type: content
  - id: 84ac3885-1b15-44fe-a922-332432beefa7
    url: 2016-07-18-contact-us.html
    name: Contact us
    type: content
  - id: 'https://bestleadsnz.getdata.biz/admin/'
    url: 'https://bestleadsnz.getdata.biz/admin/'
    name: Customer login
    type: external
